using System.Text.RegularExpressions;

namespace TFlexDrawingService.Tests;

public sealed class WindowsDeploymentScriptContractTests
{
    private static readonly string RepositoryRoot = FindRepositoryRoot();
    private static readonly string InstallerPath = Path.Combine(
        RepositoryRoot,
        "scripts",
        "Install-TFlexDrawingService.ps1");
    private static readonly string BootstrapPath = Path.Combine(
        RepositoryRoot,
        "scripts",
        "Bootstrap-WindowsServer2022.ps1");
    private static readonly string CaddyInstallerPath = Path.Combine(
        RepositoryRoot,
        "scripts",
        "Install-CaddyAcmeProxy.ps1");

    [Fact]
    public void AutoGeneratedAdminCredentialIsRecoverableAcrossRollback()
    {
        var installer = File.ReadAllText(InstallerPath);
        var bootstrap = File.ReadAllText(BootstrapPath);

        var systemSecurityLoad = installer.IndexOf(
            "Add-Type -AssemblyName System.Security -ErrorAction Stop",
            StringComparison.Ordinal);
        var protectedDataUse = installer.IndexOf(
            "[Security.Cryptography.ProtectedData]",
            StringComparison.Ordinal);

        Assert.True(systemSecurityLoad >= 0 && systemSecurityLoad < protectedDataUse);
        Assert.Contains("ProtectedData]::Protect", installer, StringComparison.Ordinal);
        Assert.Contains("DataProtectionScope]::LocalMachine", installer, StringComparison.Ordinal);
        Assert.Contains("S-1-5-18", installer, StringComparison.Ordinal);
        Assert.Contains("S-1-5-32-544", installer, StringComparison.Ordinal);
        Assert.Contains("Read-BootstrapAdminRecovery", installer, StringComparison.Ordinal);
        Assert.Contains("Write-BootstrapAdminRecovery", installer, StringComparison.Ordinal);
        Assert.Contains("Remove-BootstrapAdminRecovery", installer, StringComparison.Ordinal);

        var recoveryWrite = installer.LastIndexOf(
            "Write-BootstrapAdminRecovery `",
            StringComparison.Ordinal);
        var serviceStart = installer.IndexOf(
            "Write-Step \"Starting Windows services\"",
            StringComparison.Ordinal);
        var passwordPrint = installer.LastIndexOf(
            "bootstrap admin password:",
            StringComparison.Ordinal);
        var recoveryRemove = installer.LastIndexOf(
            "Remove-BootstrapAdminRecovery $bootstrapAdminRecoveryPath",
            StringComparison.Ordinal);

        Assert.True(recoveryWrite >= 0 && recoveryWrite < serviceStart);
        Assert.True(passwordPrint >= 0 && passwordPrint < recoveryRemove);
        Assert.Contains(
            "& $FilePath @Arguments 2>&1 | ForEach-Object",
            bootstrap,
            StringComparison.Ordinal);
        Assert.DoesNotContain(
            "$output = & $FilePath @Arguments",
            bootstrap,
            StringComparison.Ordinal);
    }

    [Fact]
    public void BootstrapDoesNotForwardBooleanAuthenticationThroughWindowsPowerShellFileBinding()
    {
        var bootstrap = File.ReadAllText(BootstrapPath);

        Assert.DoesNotContain(
            "\"-RequireAuthentication\", $RequireAuthentication.ToString()",
            bootstrap,
            StringComparison.Ordinal);
        Assert.Contains(
            "if (-not $RequireAuthentication)",
            bootstrap,
            StringComparison.Ordinal);
        Assert.Contains(
            "Windows Server production deployments require authentication.",
            bootstrap,
            StringComparison.Ordinal);
    }

    [Fact]
    public void FreshServiceInstallTreatsMissingEnvironmentRegistryValueAsEmpty()
    {
        var installer = File.ReadAllText(InstallerPath);

        Assert.DoesNotContain(
            "(Get-ItemProperty -LiteralPath $serviceKey -Name Environment -ErrorAction SilentlyContinue).Environment",
            installer,
            StringComparison.Ordinal);
        Assert.Contains(
            "$serviceProperties = Get-ItemProperty -LiteralPath $serviceKey -ErrorAction Stop",
            installer,
            StringComparison.Ordinal);
        Assert.Contains(
            "$existing = if ($null -eq $serviceProperties.Environment)",
            installer,
            StringComparison.Ordinal);
    }

    [Fact]
    public void ServiceAccountConfigurationBypassesTheCimProviderAndKeepsPasswordOutOfProcessArguments()
    {
        var installer = File.ReadAllText(InstallerPath);

        Assert.DoesNotContain(
            "Invoke-CimMethod -InputObject $service -MethodName Change",
            installer,
            StringComparison.Ordinal);
        Assert.Contains("ChangeServiceConfigW", installer, StringComparison.Ordinal);
        Assert.Contains("OpenServiceW", installer, StringComparison.Ordinal);
        Assert.Contains(
            "[TFlexDrawingService.Install.ServiceConfiguration]::SetAccount(",
            installer,
            StringComparison.Ordinal);
        Assert.Contains(
            "[System.Management.Automation.PSCredential]::new(",
            installer,
            StringComparison.Ordinal);
        Assert.Contains("-Credential $Credential", installer, StringComparison.Ordinal);
        Assert.Contains(
            "if ($currentSid -eq $ExpectedSid)",
            installer,
            StringComparison.Ordinal);
        Assert.DoesNotContain(
            "Invoke-Sc @(\"config\", $Name, \"obj=\"",
            installer,
            StringComparison.Ordinal);
    }

    [Fact]
    public void LocalServiceAccountSidIsResolvedWithoutNtAccountTranslation()
    {
        var installer = File.ReadAllText(InstallerPath);

        Assert.Contains(
            "$localUser = Get-LocalUser -Name $localUserName -ErrorAction SilentlyContinue",
            installer,
            StringComparison.Ordinal);
        Assert.Contains("return $localUser.Sid.Value", installer, StringComparison.Ordinal);
        Assert.Contains(
            "$normalizedName.StartsWith($machinePrefix, [StringComparison]::OrdinalIgnoreCase)",
            installer,
            StringComparison.Ordinal);
    }

    [Fact]
    public void RunnerReadinessIsIndependentOfRunnerBuildAndUsesProductionOverrides()
    {
        var installer = File.ReadAllText(InstallerPath);

        Assert.DoesNotMatch(
            new Regex(
                @"if\s*\([^)]*\$SkipRunnerBuild[^)]*\$SkipRunnerHealthCheck[^)]*\)",
                RegexOptions.CultureInvariant),
            installer);
        Assert.DoesNotMatch(
            new Regex(
                @"if\s*\([^)]*\$SkipRunnerHealthCheck[^)]*\$SkipRunnerBuild[^)]*\)",
                RegexOptions.CultureInvariant),
            installer);
        Assert.DoesNotContain(
            "Invoke-TFlexRunnerHealthCheck $TFlexAutomationCommandPath",
            installer,
            StringComparison.Ordinal);
        Assert.Contains(
            "HealthCheckEnabled = (-not $SkipRunnerHealthCheck)",
            installer,
            StringComparison.Ordinal);
        Assert.Contains(
            "VariableName \"TFlexAutomation__Mode\"",
            installer,
            StringComparison.Ordinal);
        Assert.Contains(
            "VariableName \"TFlexAutomation__CommandPath\"",
            installer,
            StringComparison.Ordinal);
        Assert.Contains(
            "VariableName \"TFlexAutomation__HealthCheckEnabled\"",
            installer,
            StringComparison.Ordinal);
        Assert.Contains("Assert-ReadinessUnconfirmed", installer, StringComparison.Ordinal);

        var bootstrap = File.ReadAllText(BootstrapPath);
        Assert.Contains(
            "$healthEndpoint = if ($SkipRunnerHealthCheck) { \"live\" } else { \"ready\" }",
            bootstrap,
            StringComparison.Ordinal);
        Assert.Contains("$statusCode -ne 503", bootstrap, StringComparison.Ordinal);
    }

    [Fact]
    public void HealthChecksPreserveHttpErrorResponseBodies()
    {
        var installer = File.ReadAllText(InstallerPath);
        var bootstrap = File.ReadAllText(BootstrapPath);

        foreach (var script in new[] { installer, bootstrap })
        {
            Assert.Contains(
                "function Get-HttpErrorResponseDetail",
                script,
                StringComparison.Ordinal);
            Assert.Contains(
                "$response.GetResponseStream()",
                script,
                StringComparison.Ordinal);
            Assert.Contains(
                "$reader.ReadToEnd().Trim()",
                script,
                StringComparison.Ordinal);
            Assert.Contains("[truncated]", script, StringComparison.Ordinal);
        }

        Assert.Contains(
            "$lastError = Get-HttpErrorResponseDetail $_",
            installer,
            StringComparison.Ordinal);
        Assert.Contains(
            "$lastHealthError = Get-HttpErrorResponseDetail $_",
            bootstrap,
            StringComparison.Ordinal);
    }

    [Fact]
    public void EffectiveServiceAccountAclIsAppliedAfterActivation()
    {
        var installer = File.ReadAllText(InstallerPath);

        var activation = installer.IndexOf(
            "Write-Step \"Activating staged deployment\"",
            StringComparison.Ordinal);
        var accountResolution = installer.IndexOf(
            "$apiServiceAccount = Get-ServiceAccountIdentity",
            StringComparison.Ordinal);
        var acl = installer.IndexOf(
            "Write-Step \"Configuring effective service account file access\"",
            StringComparison.Ordinal);
        var serviceStart = installer.IndexOf(
            "Write-Step \"Starting Windows services\"",
            StringComparison.Ordinal);

        Assert.True(activation >= 0);
        Assert.True(accountResolution > activation);
        Assert.True(acl > accountResolution);
        Assert.True(acl < serviceStart);
        Assert.Contains(
            "$workerServiceAccount = Get-ServiceAccountIdentity",
            installer,
            StringComparison.Ordinal);
    }

    [Fact]
    public void ServiceAccountAclLifecycleIsTransactional()
    {
        var installer = File.ReadAllText(InstallerPath);

        Assert.Contains("Get-DirectoryAclSnapshots", installer, StringComparison.Ordinal);
        Assert.Contains("Restore-DirectoryAclSnapshots", installer, StringComparison.Ordinal);
        Assert.Contains(
            "Remove-ExplicitDirectoryAccessForSid",
            installer,
            StringComparison.Ordinal);
        Assert.Contains("RemoveAccessRuleSpecific", installer, StringComparison.Ordinal);
        Assert.Contains(
            "$entry.FileSystemRights -ne $expectedRule.FileSystemRights",
            installer,
            StringComparison.Ordinal);
        Assert.Contains(
            "$entry.PropagationFlags -ne $expectedRule.PropagationFlags",
            installer,
            StringComparison.Ordinal);
        Assert.DoesNotContain("PurgeAccessRules", installer, StringComparison.Ordinal);

        var snapshot = installer.IndexOf(
            "Get-DirectoryAclSnapshots $managedAccessDirectories",
            StringComparison.Ordinal);
        var obsoleteAccessRemoval = installer.LastIndexOf(
            "Remove-ServiceFileSystemAccess `",
            StringComparison.Ordinal);
        var effectiveAcl = installer.IndexOf(
            "Write-Step \"Configuring effective service account file access\"",
            StringComparison.Ordinal);
        var deploymentFailure = installer.IndexOf(
            "Write-Warning \"Deployment validation failed: $deploymentErrorMessage Restoring the previous deployment.\"",
            StringComparison.Ordinal);
        var aclRestore = installer.IndexOf(
            "Restore-DirectoryAclSnapshots $directoryAclSnapshots",
            StringComparison.Ordinal);

        Assert.True(snapshot >= 0);
        Assert.True(obsoleteAccessRemoval > snapshot);
        Assert.True(effectiveAcl > obsoleteAccessRemoval);
        Assert.True(deploymentFailure > effectiveAcl);
        Assert.True(aclRestore > deploymentFailure);

        Assert.Contains("LsaEnumerateAccountRights", installer, StringComparison.Ordinal);
        Assert.Contains("LsaRemoveAccountRights", installer, StringComparison.Ordinal);
        Assert.Contains(
            "-GrantedByDeployment ([ref]$serviceLogonRightGrantedByDeployment)",
            installer,
            StringComparison.Ordinal);
        Assert.Contains(
            "Remove-LogOnAsServiceRightIfUnused",
            installer,
            StringComparison.Ordinal);
        Assert.Contains("Test-ServiceAccountSidInUse", installer, StringComparison.Ordinal);

        var rollbackPossible = installer.LastIndexOf(
            "Assert-ServiceAccountRollbackPossible",
            StringComparison.Ordinal);
        var rightGrant = installer.IndexOf(
            "Grant-LogOnAsServiceRight `",
            StringComparison.Ordinal);
        var rightRollback = installer.LastIndexOf(
            "Remove-LogOnAsServiceRightIfUnused `",
            StringComparison.Ordinal);

        Assert.True(rightGrant > rollbackPossible);
        Assert.True(rightRollback > deploymentFailure);
    }

    [Fact]
    public void DeploymentRollbackPreservesThePrimaryFailureMessage()
    {
        var installer = File.ReadAllText(InstallerPath);

        var catchStart = installer.IndexOf(
            "$deploymentError = $_",
            StringComparison.Ordinal);
        var rollbackWarning = installer.IndexOf(
            "Deployment validation failed: $deploymentErrorMessage",
            StringComparison.Ordinal);
        var finalFailure = installer.LastIndexOf(
            "Deployment failed: $deploymentErrorMessage The previous deployment was restored.",
            StringComparison.Ordinal);

        Assert.True(catchStart >= 0 && catchStart < rollbackWarning);
        Assert.True(rollbackWarning < finalFailure);
        Assert.Contains(
            "sc.exe failed with exit code $LASTEXITCODE`: $details",
            installer,
            StringComparison.Ordinal);
    }

    [Fact]
    public void StagedTemplateFilesAreValidatedBeforeServicesStop()
    {
        var installer = File.ReadAllText(InstallerPath);

        Assert.Contains("function Assert-StagedTemplateFiles", installer, StringComparison.Ordinal);
        Assert.Contains("$templates = @($Catalog.templates", installer, StringComparison.Ordinal);
        Assert.Contains("Staged template catalog is empty.", installer, StringComparison.Ordinal);
        Assert.Contains("foreach ($template in $templates)", installer, StringComparison.Ordinal);
        Assert.Contains(
            "$resolvedLiveTemplatePath.StartsWith(",
            installer,
            StringComparison.Ordinal);
        Assert.Contains(
            "$stagedTemplatePath.StartsWith(",
            installer,
            StringComparison.Ordinal);
        Assert.Contains(
            "Test-Path -LiteralPath $stagedTemplatePath -PathType Leaf",
            installer,
            StringComparison.Ordinal);
        Assert.Contains(
            "Staged template '$templateCode' references unsafe templateFilePath '$templatePath'.",
            installer,
            StringComparison.Ordinal);
        Assert.Contains(
            "Staged template '$templateCode' references missing staged file '$templatePath'",
            installer,
            StringComparison.Ordinal);

        var catalogParse = installer.IndexOf(
            "$templateCatalog = Get-Content -LiteralPath (Join-Path $TemplatesDirectory \"templates.json\") -Encoding UTF8 -Raw | ConvertFrom-Json",
            StringComparison.Ordinal);
        var stagedFileValidation = installer.IndexOf(
            "Assert-StagedTemplateFiles `",
            catalogParse,
            StringComparison.Ordinal);
        var firstDeploymentValidation = installer.IndexOf(
            "Assert-StagedDeployment `",
            stagedFileValidation,
            StringComparison.Ordinal);
        var servicesStop = installer.IndexOf(
            "Write-Step \"Stopping services after staging validation\"",
            StringComparison.Ordinal);

        Assert.True(catalogParse >= 0);
        Assert.True(stagedFileValidation > catalogParse);
        Assert.True(firstDeploymentValidation > stagedFileValidation);
        Assert.True(firstDeploymentValidation < servicesStop);
    }

    [Fact]
    public void DeploymentJsonIsAlwaysReadAsUtf8()
    {
        var installer = File.ReadAllText(InstallerPath);
        var jsonReadLines = installer
            .Split('\n')
            .Where(line => line.Contains("Get-Content", StringComparison.Ordinal)
                && line.Contains("ConvertFrom-Json", StringComparison.Ordinal))
            .ToArray();

        Assert.NotEmpty(jsonReadLines);
        Assert.All(
            jsonReadLines,
            line => Assert.Contains("-Encoding UTF8", line, StringComparison.Ordinal));
        Assert.Contains(
            "$stagedCatalog = Get-Content -LiteralPath $stagedCatalogPath -Encoding UTF8 -Raw | ConvertFrom-Json",
            installer,
            StringComparison.Ordinal);
    }

    [Fact]
    public void PrivilegedDownloadsArePinnedAndVerifiedBeforeUse()
    {
        var bootstrap = File.ReadAllText(BootstrapPath);

        Assert.Contains("function Invoke-VerifiedDownload", bootstrap, StringComparison.Ordinal);
        Assert.Contains("-MaximumRedirection 5", bootstrap, StringComparison.Ordinal);
        Assert.Contains(
            "$downloadResponse.BaseResponse.ResponseUri",
            bootstrap,
            StringComparison.Ordinal);
        Assert.Contains(
            "$normalizedAllowedHosts -notcontains $finalHost",
            bootstrap,
            StringComparison.Ordinal);
        Assert.Contains(
            "Get-FileHash -LiteralPath $DestinationPath -Algorithm SHA256",
            bootstrap,
            StringComparison.Ordinal);
        Assert.Contains(
            "Get-AuthenticodeSignature -LiteralPath $DestinationPath",
            bootstrap,
            StringComparison.Ordinal);
        Assert.Contains("$DotNetSdkVersion = \"10.0.302\"", bootstrap, StringComparison.Ordinal);
        Assert.Contains(
            "$DotNetInstallScriptUrl = \"https://builds.dotnet.microsoft.com/dotnet/scripts/v1/dotnet-install.ps1\"",
            bootstrap,
            StringComparison.Ordinal);
        Assert.Contains(
            "$DotNetInstallScriptSha256 = \"6585899aed55ff6ae13dbe1e8c3b878f2d00433520e7efbe250b75db948b7da9\"",
            bootstrap,
            StringComparison.Ordinal);
        Assert.Contains(
            "$DotNetInstallScriptAllowedHosts = @(\"builds.dotnet.microsoft.com\")",
            bootstrap,
            StringComparison.Ordinal);
        Assert.Contains(
            "$GitForWindowsVersion = \"2.55.0.3\"",
            bootstrap,
            StringComparison.Ordinal);
        Assert.Contains(
            "$GitForWindowsInstallerUrl = \"https://github.com/git-for-windows/git/releases/download/v2.55.0.windows.3/Git-2.55.0.3-64-bit.exe\"",
            bootstrap,
            StringComparison.Ordinal);
        Assert.Contains(
            "$GitForWindowsInstallerSha256 = \"af12577d0fdff74243a5988197aa49b957d5044edc17004f6ddf0768996f1dca\"",
            bootstrap,
            StringComparison.Ordinal);
        Assert.Contains(
            "$GitForWindowsInstallerAllowedHosts = @(\"github.com\", \"release-assets.githubusercontent.com\")",
            bootstrap,
            StringComparison.Ordinal);
        Assert.Contains(
            "$VisualStudioBuildToolsVersion = \"17.14.36\"",
            bootstrap,
            StringComparison.Ordinal);
        Assert.Contains(
            "$VisualStudioBuildToolsUrl = \"https://download.visualstudio.microsoft.com/download/pr/12aa1305-dd17-4f26-8429-d072cda64c80/5ae95bb02bb3442441a8d891e5bb1d2975445e2e3ee16ada5bc7bd17227f1dd7/vs_BuildTools.exe\"",
            bootstrap,
            StringComparison.Ordinal);
        Assert.Contains(
            "$VisualStudioBuildToolsSha256 = \"5ae95bb02bb3442441a8d891e5bb1d2975445e2e3ee16ada5bc7bd17227f1dd7\"",
            bootstrap,
            StringComparison.Ordinal);
        Assert.Contains(
            "$VisualStudioBuildToolsAllowedHosts = @(\"download.visualstudio.microsoft.com\")",
            bootstrap,
            StringComparison.Ordinal);
        Assert.Contains(
            "$NetFx472DeveloperPackUrl = \"https://download.microsoft.com/download/7/1/7/71795fde-1cca-41b0-b495-00b1ab656994/NDP472-DevPack-ENU.exe\"",
            bootstrap,
            StringComparison.Ordinal);
        Assert.Contains(
            "$NetFx472DeveloperPackSha256 = \"1fa87cc7135a5360fd8b692b5118ec60963d4ce73db4a996ca62afa2b5623a6b\"",
            bootstrap,
            StringComparison.Ordinal);
        Assert.Contains(
            "$NetFx472DeveloperPackAllowedHosts = @(\"download.microsoft.com\")",
            bootstrap,
            StringComparison.Ordinal);
        Assert.Equal(
            4,
            Regex.Matches(
                bootstrap,
                @"(?m)^\s*Invoke-VerifiedDownload\s+`",
                RegexOptions.CultureInvariant).Count);
        Assert.Equal(
            3,
            Regex.Matches(
                bootstrap,
                @"(?m)^\s*-ExpectedPublisher \$MicrosoftPublisher\s*$",
                RegexOptions.CultureInvariant).Count);
        Assert.DoesNotContain(
            "api.github.com/repos/git-for-windows/git/releases/latest",
            bootstrap,
            StringComparison.Ordinal);
        Assert.DoesNotContain("aka.ms/vs/17/release", bootstrap, StringComparison.Ordinal);
        Assert.DoesNotContain(
            "go.microsoft.com/fwlink/?linkid=874338",
            bootstrap,
            StringComparison.Ordinal);

        var bootstrapFinalHostCheck = bootstrap.IndexOf(
            "$normalizedAllowedHosts -notcontains $finalHost",
            StringComparison.Ordinal);
        var bootstrapHashCheck = bootstrap.IndexOf(
            "Get-FileHash -LiteralPath $DestinationPath -Algorithm SHA256",
            StringComparison.Ordinal);
        Assert.True(bootstrapFinalHostCheck >= 0);
        Assert.True(bootstrapHashCheck > bootstrapFinalHostCheck);

        var caddyInstaller = File.ReadAllText(CaddyInstallerPath);

        Assert.Contains(
            "$CaddyVersion = \"2.11.4\"",
            caddyInstaller,
            StringComparison.Ordinal);
        Assert.Contains(
            "$CaddyArchiveUrl = \"https://github.com/caddyserver/caddy/releases/download/v2.11.4/caddy_2.11.4_windows_amd64.zip\"",
            caddyInstaller,
            StringComparison.Ordinal);
        Assert.Contains(
            "$CaddyArchiveSha256 = \"1708333f79e274c7697285afe6d592ab39314e0b131e9ec6bea08ad27df62ebf\"",
            caddyInstaller,
            StringComparison.Ordinal);
        Assert.Contains(
            "$CaddyArchiveAllowedHosts = @(\"github.com\", \"release-assets.githubusercontent.com\")",
            caddyInstaller,
            StringComparison.Ordinal);
        Assert.Contains("-MaximumRedirection 5", caddyInstaller, StringComparison.Ordinal);
        Assert.Single(
            Regex.Matches(
                    caddyInstaller,
                    @"(?m)^\s*Invoke-VerifiedDownload\s+`",
                    RegexOptions.CultureInvariant)
                .Cast<Match>());
        Assert.DoesNotContain(
            "api.github.com/repos/caddyserver/caddy/releases/latest",
            caddyInstaller,
            StringComparison.Ordinal);
        Assert.DoesNotContain(
            "$asset.browser_download_url",
            caddyInstaller,
            StringComparison.Ordinal);

        var caddyFinalHostCheck = caddyInstaller.IndexOf(
            "$normalizedAllowedHosts -notcontains $finalHost",
            StringComparison.Ordinal);
        var caddyHashCheck = caddyInstaller.IndexOf(
            "Get-FileHash -LiteralPath $DestinationPath -Algorithm SHA256",
            StringComparison.Ordinal);
        var caddyVerification = caddyInstaller.LastIndexOf(
            "Invoke-VerifiedDownload `",
            StringComparison.Ordinal);
        var caddyExpansion = caddyInstaller.IndexOf(
            "Expand-Archive -LiteralPath $archivePath",
            StringComparison.Ordinal);
        Assert.True(caddyFinalHostCheck >= 0);
        Assert.True(caddyHashCheck > caddyFinalHostCheck);
        Assert.True(caddyVerification >= 0);
        Assert.True(caddyExpansion > caddyVerification);
    }

    private static string FindRepositoryRoot()
    {
        for (var directory = new DirectoryInfo(AppContext.BaseDirectory);
             directory is not null;
             directory = directory.Parent)
        {
            if (File.Exists(Path.Combine(
                    directory.FullName,
                    "scripts",
                    "Install-TFlexDrawingService.ps1")))
            {
                return directory.FullName;
            }
        }

        throw new DirectoryNotFoundException(
            "Could not locate the repository root containing Windows deployment scripts.");
    }
}
